name: image_analyzer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  #sdk: ">=2.17.0 <3.0.0"
  sdk: '>=3.1.3 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  #image_picker: ^1.0.5
  scanning_effect: ^1.0.4
  image_editor: ^1.3.0
  crop_image: ^1.0.11
  image_cropper: ^5.0.1
  #image_editor_plus: ^1.0.5
  #image_editor_dove: ^0.0.3
  flutter_image_filters: ^0.0.17
  colorfilter_generator: ^0.0.8
  on_image_matrix: ^1.0.0+1
  #image: ^3.0.1
  #image_compare: ^1.1.2
  flutter_isolate: ^2.0.4
  flutter_image_editor: ^2.1.0
  widgets_to_image: ^0.0.2
  loading_animations: ^2.2.0
  flutter_pixelmatching: ^1.0.0
  #opencv_4: ^1.0.0
  #extended_image: ^8.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
